skaffold.yaml

This was causing random HTTP Gateway errors (502) when doing HTTP requests to the backend.

limit scope of nginx ingress

---

charts/hlf-k8s/README.md
charts/hlf-k8s/templates/configmap-fabric.yaml
charts/hlf-k8s/templates/job-bootstrap-orderer.yaml
charts/hlf-k8s/templates/job-bootstrap-peer.yaml
charts/hlf-k8s/templates/job-hook-cleanup.yaml
charts/hlf-k8s/values.yaml
images/hlf-k8s/bin/bootstrap.sh
skaffold.yaml

Linked to https://github.com/SubstraFoundation/substra-frontend/pull/24 and https://github.com/SubstraFoundation/substra-backend/pull/35

Clean charts

---

.travis.yml

See https://github.com/SubstraFoundation/substra-backend/pull/48

travis: remove --client-only from helm init

---

python-scripts/conf/chunantes/peers/peer1.py
python-scripts/conf/chunantes/peers/peer2.py
python-scripts/conf/clb/peers/peer1.py
python-scripts/conf/clb/peers/peer2.py
python-scripts/conf/owkin/peers/peer1.py
python-scripts/conf/owkin/peers/peer2.py

Update prometheuse ports

---

README.md

This PR started with a typofix on "susbtra" and ended with some markdown linting and minor tweaks. Please, do not hesitate to suggest edits!

Typofix & markdown lint

---

charts/hlf-k8s/templates/deployment-enrollement-operator.yaml
images/hlf-k8s/Dockerfile

This allows the enrollment operator to run even without internet access﻿.

Enrollment: don't download binaries

---

README.md
charts/hlf-k8s/templates/deployment-chaincode-operator.yaml

fix install local chaincode

---

charts/hlf-k8s/Chart.yaml
charts/hlf-k8s/templates/configmap-application-organization.yaml
charts/hlf-k8s/templates/configmap-application-proposal-organization.yaml
charts/hlf-k8s/templates/configmap-system-organizations.yaml
charts/hlf-k8s/templates/deployment-application-channel-operator.yaml
charts/hlf-k8s/templates/deployment-system-channel-operator.yaml
charts/hlf-k8s/values.yaml
skaffold.yaml
tools/skaffold-3orgs.yaml
tools/skaffold-4orgs-policy-any.yaml
tools/skaffold-4orgs.yaml

NB: I've not tested it currently !

Improve channel operators

---

charts/hlf-k8s/Chart.yaml
charts/hlf-k8s/templates/deployment-monitor.yaml
charts/hlf-k8s/values.yaml
skaffold.yaml

Add discover monitoring for membership view
Fix channel monitoring for orderer

Add discover monitoring

---

README.md
charts/hlf-k8s/CHANGELOG.md
charts/hlf-k8s/Chart.yaml
charts/hlf-k8s/README.md
charts/hlf-k8s/templates/configmap-application-organization.yaml
charts/hlf-k8s/templates/configmap-application-proposal-organization.yaml
charts/hlf-k8s/templates/configmap-fabric.yaml
charts/hlf-k8s/templates/deployment-appchannel-operator.yaml
charts/hlf-k8s/templates/deployment-monitor.yaml
charts/hlf-k8s/templates/ingress-application-channel.yaml
charts/hlf-k8s/values.yaml
skaffold.yaml
tools/skaffold-3orgs.yaml
tools/skaffold-4orgs-policy-any.yaml
tools/skaffold-4orgs.yaml

**TL;DR**: Make `appChannel` a list.
- @ClementGautier Please note that this is a [breaking change](https://github.com/SubstraFoundation/hlf-k8s/pull/75/files#diff-fcbde7c13ef662a06d6249e260a01a95R13)
- @thibaultrobert FYI
---
**Supports adding new channels on the fly:**
1. `skaffold run`
2. Edit skaffold.yaml
Add the following lines:
```yaml
appChannels[1].channelName: yourchannel
appChannels[1].channelName: yourchannel
appChannels[1].organizations[0].org: MyOrg1
appChannels[1].organizations[0].mspid: MyOrg1MSP
appChannels[1].organizations[0].configUrl: network-org-1-peer-1-hlf-k8s-config-operator.org-1/config/configOrgWithAnchors.json
appChannels[1].organizations[1].org: MyOrg2
appChannels[1].organizations[1].mspid: MyOrg2MSP
appChannels[1].organizations[1].configUrl: …
```

Add support for multi-channel setups

---

skaffold.yaml

Create two channel by default. Companion PR: https://github.com/SubstraFoundation/substra-backend/pull/284

Create two channels by default

---

charts/hlf-k8s/Chart.yaml
charts/hlf-k8s/templates/configmap-fabric.yaml
charts/hlf-k8s/values.yaml

Update `MaxMessageCount` and `BatchTimeout` to increase transaction throughput of the ledger
More information about those values can be found in hyperledger [documentation](https://hyperledger-fabric.readthedocs.io/en/release-1.4/config_update.html#editing-a-config).

Update message per block

---

charts/hlf-k8s/Chart.yaml
charts/hlf-k8s/requirements.lock
charts/hlf-k8s/requirements.yaml

Bump hlf-peer chart

---

charts/hlf-k8s/requirements.lock
charts/hlf-k8s/requirements.yaml

Bumping the hlf charts to the last version available.﻿

Bump hlf-peer and hlf-ord

---

charts/hlf-k8s/Chart.yaml
charts/hlf-k8s/templates/deployment-appchannel-operator.yaml

This PR fixes a typo preventing the add anchor procedure from being executed.

Fix add anchor

---

charts/hlf-k8s/README.md
charts/hlf-k8s/values.yaml
examples/2-orgs-policy-any-no-ca/values/org-1-peer-1.yaml
examples/2-orgs-policy-any-no-ca/values/org-2-peer-1.yaml
examples/2-orgs-policy-any/values/org-1-peer-1.yaml
examples/2-orgs-policy-any/values/org-2-peer-1.yaml
examples/3-orgs-policy-majority/values/org-1-peer-1.yaml
examples/3-orgs-policy-majority/values/org-2-peer-1.yaml
examples/3-orgs-policy-majority/values/org-3-peer-1.yaml
examples/4-orgs-policy-any/values/org-1-peer-1.yaml
examples/4-orgs-policy-any/values/org-2-peer-1.yaml
examples/4-orgs-policy-any/values/org-3-peer-1.yaml
examples/4-orgs-policy-any/values/org-4-peer-1.yaml
examples/4-orgs-policy-majority/values/org-1-peer-1.yaml
examples/4-orgs-policy-majority/values/org-2-peer-1.yaml
examples/4-orgs-policy-majority/values/org-3-peer-1.yaml
examples/4-orgs-policy-majority/values/org-4-peer-1.yaml

Update chaincode version value to the last one in examples
None
https://github.com/SubstraFoundation/substra-backend/pull/352
https://github.com/SubstraFoundation/substra-chaincode/pull/131
None
None
None

Update chaincode version

---

charts/hlf-k8s/CHANGELOG.md
charts/hlf-k8s/Chart.yaml
charts/hlf-k8s/templates/deployment-chaincode-operator.yaml
examples/2-orgs-policy-any-no-ca-same-cc/skaffold.yaml
examples/2-orgs-policy-any-no-ca-same-cc/values/orderer.yaml
examples/2-orgs-policy-any-no-ca-same-cc/values/org-1-peer-1.yaml
examples/2-orgs-policy-any-no-ca-same-cc/values/org-2-peer-1.yaml
examples/2-orgs-policy-any-no-ca/skaffold.yaml

If we use the same chaincode for two different channels, some chaincode operator conditions failed and loop indefinitely because condition is base only on chaincode attributes.
This PR aims to make condition unique for each channel, even if chaincode is the same.
None
None
Launch new example.
None
None

Fix chaincode operator

---

README.md

Bump skaffold version in `README.md` to `v1.20.x`.
In #124 I updated the Skaffold files but forgot to update the skaffold version mentioned in the `README.md`, making the setup unable to work by following the documentation.
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

Update Skaffold version in README

---

examples/2-orgs-policy-any-no-ca-same-cc/values/orderer.yaml
examples/2-orgs-policy-any-no-ca-same-cc/values/org-1-peer-1.yaml
examples/2-orgs-policy-any-no-ca-same-cc/values/org-2-peer-1.yaml
examples/2-orgs-policy-any-no-ca/values/orderer.yaml
examples/2-orgs-policy-any-no-ca/values/org-1-peer-1.yaml
examples/2-orgs-policy-any-no-ca/values/org-2-peer-1.yaml
examples/2-orgs-policy-any/values/orderer.yaml
examples/2-orgs-policy-any/values/org-1-peer-1.yaml
examples/2-orgs-policy-any/values/org-2-peer-1.yaml
examples/3-orgs-policy-majority/values/orderer.yaml
examples/3-orgs-policy-majority/values/org-1-peer-1.yaml
examples/3-orgs-policy-majority/values/org-2-peer-1.yaml
examples/3-orgs-policy-majority/values/org-3-peer-1.yaml
examples/4-orgs-policy-any/values/orderer.yaml
examples/4-orgs-policy-any/values/org-1-peer-1.yaml
examples/4-orgs-policy-any/values/org-2-peer-1.yaml
examples/4-orgs-policy-any/values/org-3-peer-1.yaml
examples/4-orgs-policy-any/values/org-4-peer-1.yaml
examples/4-orgs-policy-majority/values/orderer.yaml
examples/4-orgs-policy-majority/values/org-1-peer-1.yaml
examples/4-orgs-policy-majority/values/org-2-peer-1.yaml
examples/4-orgs-policy-majority/values/org-3-peer-1.yaml
examples/4-orgs-policy-majority/values/org-4-peer-1.yaml

Remove nginx-ingress from examples values that remain after #124

Remove nginx-ingress from examples values

---

charts/hlf-k8s/README.md
charts/hlf-k8s/UPGRADE.md
charts/hlf-k8s/values.yaml
examples/2-orgs-policy-any-no-ca-same-cc/values/orderer.yaml
examples/2-orgs-policy-any-no-ca-same-cc/values/org-1-peer-1.yaml
examples/2-orgs-policy-any-no-ca/values/org-2-peer-1.yaml
examples/2-orgs-policy-any/values/orderer.yaml
examples/3-orgs-policy-majority/values/org-2-peer-1.yaml
examples/4-orgs-policy-majority/values/orderer.yaml

Follow-up to https://github.com/SubstraFoundation/hlf-k8s/pull/128

doc/chore: add missing .svc.cluster.local

---

charts/hlf-k8s/README.md
charts/hlf-k8s/values.yaml
examples/2-orgs-policy-any-no-ca-same-cc/values/org-1-peer-1.yaml
examples/2-orgs-policy-any-no-ca-same-cc/values/org-2-peer-1.yaml
examples/2-orgs-policy-any-no-ca/values/org-1-peer-1.yaml
examples/2-orgs-policy-any-no-ca/values/org-2-peer-1.yaml
examples/2-orgs-policy-any/values/org-1-peer-1.yaml
examples/2-orgs-policy-any/values/org-2-peer-1.yaml
examples/3-orgs-policy-majority/values/org-1-peer-1.yaml
examples/3-orgs-policy-majority/values/org-2-peer-1.yaml
examples/3-orgs-policy-majority/values/org-3-peer-1.yaml
examples/4-orgs-policy-any/values/org-1-peer-1.yaml
examples/4-orgs-policy-any/values/org-2-peer-1.yaml
examples/4-orgs-policy-any/values/org-3-peer-1.yaml
examples/4-orgs-policy-any/values/org-4-peer-1.yaml
examples/4-orgs-policy-majority/values/org-1-peer-1.yaml
examples/4-orgs-policy-majority/values/org-2-peer-1.yaml
examples/4-orgs-policy-majority/values/org-3-peer-1.yaml
examples/4-orgs-policy-majority/values/org-4-peer-1.yaml

Update substra-chaincode version in example values

chore: update example chaincode values to 0.3.0

---

.github/workflows/docker.yml
.github/workflows/helm.yml
charts/hlf-k8s/CHANGELOG.md
charts/hlf-k8s/Chart.yaml

- publish images on ghcr.io
- update chart metadata
- publish chart on substra repo

ci: update workflows

---

charts/hlf-k8s/CHANGELOG.md
charts/hlf-k8s/Chart.yaml
charts/hlf-k8s/README.md
charts/hlf-k8s/values.yaml
examples/2-orgs-policy-any-no-ca-same-cc/values/org-1-peer-1.yaml
examples/2-orgs-policy-any-no-ca-same-cc/values/org-2-peer-1.yaml
examples/2-orgs-policy-any-no-ca/values/org-1-peer-1.yaml
examples/2-orgs-policy-any-no-ca/values/org-2-peer-1.yaml
examples/2-orgs-policy-any/values/org-1-peer-1.yaml
examples/2-orgs-policy-any/values/org-2-peer-1.yaml
examples/3-orgs-policy-majority/values/org-1-peer-1.yaml
examples/3-orgs-policy-majority/values/org-2-peer-1.yaml
examples/3-orgs-policy-majority/values/org-3-peer-1.yaml
examples/4-orgs-policy-any/values/org-1-peer-1.yaml
examples/4-orgs-policy-any/values/org-2-peer-1.yaml
examples/4-orgs-policy-any/values/org-3-peer-1.yaml
examples/4-orgs-policy-any/values/org-4-peer-1.yaml
examples/4-orgs-policy-majority/values/org-1-peer-1.yaml
examples/4-orgs-policy-majority/values/org-2-peer-1.yaml
examples/4-orgs-policy-majority/values/org-3-peer-1.yaml
examples/4-orgs-policy-majority/values/org-4-peer-1.yaml
skaffold.yaml

Update image registry to use public images.
Tested fine locally.

chore: update image registry

---

CHANGELOG.md
charts/hlf-k8s/CHANGELOG.md
charts/hlf-k8s/Chart.yaml
charts/hlf-k8s/README.md
charts/hlf-k8s/values.yaml

New open source release to make the release of Substra complete.

chore: release 0.2.2

---

CHANGELOG.md
charts/hlf-k8s/CHANGELOG.md
charts/hlf-k8s/Chart.yaml
charts/hlf-k8s/README.md
charts/hlf-k8s/values.yaml

Signed-off-by: Guilhem Barthes <guilhem.barthes@owkin.com>

release: 0.2.3

---

CHANGELOG.md
charts/hlf-k8s/CHANGELOG.md
charts/hlf-k8s/Chart.yaml
charts/hlf-k8s/README.md
charts/hlf-k8s/values.yaml

- Update libcurl in fabric-tools image ([#151](https://github.com/Substra/hlf-k8s/pull/151))

chore: release 0.2.4
