- README.md
- charts/hlf-k8s/templates/job-chaincode-install.yaml
- charts/hlf-k8s/values.yaml
- images/hlf-k8s/bin/chaincode-install.sh
- skaffold.yaml
The network currently downloads the chaincode source code from the public internet on each startup.
This PR allows developers to instruct hlf-k8s to fetch the chaincode source code from a local folder.
This can be useful to test local chaincode changes. This also allows developers to start the network without an internet acccess.
> chaincode: support local filepath for chaincode source code (in addition to archive URL)

- skaffold.yaml
This update of the chaincode repo branch is necessary as we move from a git flow to a github flow.
The `dev` branch will be removed in the future, so it won't be possible to download the chaincode archive from github on this branch.
> Update chaincode repo branch from dev to master.

- charts/hlf-k8s/templates/job-chaincode-install.yaml
As reported by @AurelienGasser on slack, there is a github token left in the code (https://owkin.slack.com/archives/GEEGYPC2C/p1574331329001600)
> Remove pre-opensourcing Github Token

- images/hlf-k8s/setup-hfc-binaries.sh
- images/substra-ca-tools-debug/bootstrap-binaries.sh
- images/substra-ca-tools/bootstrap-binaries.sh
Issue : https://github.com/SubstraFoundation/substra/issues/111
Nexus seems to be unavailable and binaries are now download from github 
Based on https://github.com/hyperledger/fabric/blob/master/scripts/bootstrap.sh
> Fix boostrap binaries.

- .travis.yml
- charts/hlf-k8s/Chart.yaml
This will prevent from overriding the hlf-k8s chart with an unstable version.
> Update travis file to build only the master branch

- charts/hlf-k8s/Chart.yaml
- charts/hlf-k8s/README.md
- charts/hlf-k8s/templates/deployment-chaincode-operator.yaml
- charts/hlf-k8s/values.yaml
- skaffold.yaml
- tools/skaffold-3orgs.yaml
- tools/skaffold-4orgs.yaml
This removes the need for internet in the chaincode operator
Testing:
```
curl -L https://github.com/SubstraFoundation/substra-chaincode/archive/master.tar.gz -o chaincode.tar.gz
kubectl create configmap hlf-chaincode --from-file=chaincode.tar.gz -n org-1
```
Then in skaffold.yaml (peer 1)
```
chaincodes[0].configMap.name: hlf-chaincode
chaincodes[0].configMap.fileName: chaincode.tar.gz
```
> Add ConfigMap option for chaincode

- charts/hlf-k8s/templates/deployment-genesis-operator.yaml
kubectl is part of the hlf-k8s docker image now
> Remove unneeded curl

- charts/hlf-k8s/Chart.yaml
- charts/hlf-k8s/README.md
- charts/hlf-k8s/templates/deployment-toolbox.yaml
- charts/hlf-k8s/templates/job-hook-delete-secrets.yaml
- charts/hlf-k8s/templates/job-hook-uninstall-chaincode.yaml
- charts/hlf-k8s/templates/rbac.yaml
- charts/hlf-k8s/values.yaml
- skaffold.yaml
- tools/skaffold-3orgs.yaml
- tools/skaffold-4orgs-policy-any.yaml
- tools/skaffold-4orgs.yaml
A bunch of changes:
- Remove unnecessary rbac capabilities ("resources")
- Change from using a `ClusterRole` to using a `Role`﻿
- rename hook files
- make hooks disabled by default (uninstall chaincode + delete secrets), but enable them in skaffold
- make toolbox disabled by default, but enable it in skaffold
> Disable hooks and toolbox by default + remove ClusterRole

- charts/hlf-k8s/Chart.yaml
- charts/hlf-k8s/README.md
- charts/hlf-k8s/requirements.lock
- charts/hlf-k8s/requirements.yaml
- charts/hlf-k8s/templates/configmap-application-organization.yaml
- charts/hlf-k8s/templates/configmap-application-proposal-organization.yaml
- charts/hlf-k8s/templates/configmap-fabric.yaml
- charts/hlf-k8s/templates/configmap-system-organizations.yaml
- charts/hlf-k8s/templates/deployment-application-channel-operator.yaml
- charts/hlf-k8s/templates/deployment-chaincode-operator.yaml
- charts/hlf-k8s/templates/deployment-config-operator.yaml
- charts/hlf-k8s/templates/deployment-enrollement-operator.yaml
- charts/hlf-k8s/templates/deployment-genesis-operator.yaml
- charts/hlf-k8s/templates/deployment-monitor.yaml
- charts/hlf-k8s/templates/deployment-system-channel-operator.yaml
- charts/hlf-k8s/templates/job-hook-uninstall-chaincode.yaml
- charts/hlf-k8s/values.yaml
- skaffold.yaml
- tools/skaffold-3orgs.yaml
- tools/skaffold-4orgs-policy-any.yaml
- tools/skaffold-4orgs.yaml
- tools/test-dev-network.sh
Companion PR: https://github.com/SubstraFoundation/substra-backend/pull/246
Remove all aliases to avoid potential issue with helm issue with subchart aliases
You can deploy with skaffold (2, 3, 4 orgs) and test it with :
```bash
#!/bin/bash
for i in {1..4}; do
kubectl exec -it -n org-$i `kubectl get pods -n org-$i | grep toolbox | cut -d' ' -f1` -- \
bash -c "peer chaincode invoke \
-C mychannel \
-n mycc \
--tls \
--clientauth \
--cafile /var/hyperledger/tls/ord/cert/cacert.pem \
--certfile /var/hyperledger/tls/server/pair/tls.crt \
--keyfile /var/hyperledger/tls/server/pair/tls.key \
-o network-orderer-hlf-ord.orderer:7050 \
-c '{\"Args\":[\"queryTraintuples\"]}'"
done
```
> Remove all aliases

- charts/hlf-k8s/Chart.yaml
- charts/hlf-k8s/templates/deployment-system-channel-operator.yaml
Before we where not looking in the correct file to check if a partner was already present in the system channel. So we executed the loop content even if the partner was already present.
> fix system channel present partner verification

- charts/hlf-k8s/Chart.yaml
- charts/hlf-k8s/values.yaml
Follow-up to https://github.com/SubstraFoundation/hlf-k8s/pull/76
Fixes hlf-k8s being non-functional following the removal of `:latest` image(s) by hyperledger.
> Specify HLF chaincode images

- .travis.yml
- k8s/serviceAccount-orderer.yaml
- k8s/serviceAccount-org-1.yaml
- k8s/serviceAccount-org-2.yaml
- skaffold.yaml
- tools/k8s/serviceAccount-org-3.yaml
- tools/k8s/serviceAccount-org-4.yaml
- tools/skaffold-3orgs.yaml
- tools/skaffold-4orgs-policy-any.yaml
- tools/skaffold-4orgs.yaml
As we added some yaml files to the repo it seems important to lint them to avoid mistakes and catch early indentation issues, empty values or anything else that could be missed by a human reviewer.
> Lint yaml files

- .travis.yml
- charts/hlf-k8s/CHANGELOG.md
- charts/hlf-k8s/Chart.yaml
- charts/hlf-k8s/README.md
- charts/hlf-k8s/templates/job-hook-delete-secrets.yaml
- charts/hlf-k8s/values.yaml
- k8s/README.md
- k8s/serviceAccount-orderer.yaml
- k8s/serviceAccount-org-1.yaml
- k8s/serviceAccount-org-2.yaml
- skaffold.yaml
- tools/k8s/serviceAccount-org-3.yaml
- tools/k8s/serviceAccount-org-4.yaml
- tools/skaffold-3orgs.yaml
- tools/skaffold-4orgs-policy-any.yaml
- tools/skaffold-4orgs.yaml
Switching from **Helm2** to **Helm3** no major change was done to the hlf-k8s Helm chart. The only modification needed was to change the post-delete Helm hook that we had to delete secrets created by the app.
There is no more Tiller since **Helm3** so we can't use the `tiller` `serviceAccount` for our post-delete hooks but we still need a `serviceAccount` with the permissions to delete Kubernetes secrets.
The service account used to delete the Kubernetes secrets is now a value that you can set to use your own service account.
> ℹ️ Note that the serviceAccount is a namespaced ressource and needs to be located in the same namespace as your deployment.
As there was no major change the chart is still compatible with **Helm2** even if **Helm3** will now be prefered for deployment and in the …
> Switch from Helm2 to Helm3

- charts/hlf-k8s/Chart.yaml
- charts/hlf-k8s/README.md
- charts/hlf-k8s/values.yaml
- examples/2-orgs-policy-any-no-ca/values/org-1-peer-1.yaml
- examples/2-orgs-policy-any-no-ca/values/org-2-peer-1.yaml
- examples/2-orgs-policy-any/values/org-1-peer-1.yaml
- examples/2-orgs-policy-any/values/org-2-peer-1.yaml
- examples/3-orgs-policy-majority/values/org-1-peer-1.yaml
- examples/3-orgs-policy-majority/values/org-2-peer-1.yaml
- examples/3-orgs-policy-majority/values/org-3-peer-1.yaml
- examples/4-orgs-policy-any/values/org-1-peer-1.yaml
- examples/4-orgs-policy-any/values/org-2-peer-1.yaml
- examples/4-orgs-policy-any/values/org-3-peer-1.yaml
- examples/4-orgs-policy-any/values/org-4-peer-1.yaml
- examples/4-orgs-policy-majority/values/org-1-peer-1.yaml
- examples/4-orgs-policy-majority/values/org-2-peer-1.yaml
- examples/4-orgs-policy-majority/values/org-3-peer-1.yaml
- examples/4-orgs-policy-majority/values/org-4-peer-1.yaml
Update substra-chaincode default tag to 0.1.0
@AlexandrePicosson Is it possible to remove substra-chaince image `hlf-2` tag in dockerhub ?
> Update substra-chaincode tag

- charts/hlf-k8s/CHANGELOG.md
- charts/hlf-k8s/Chart.yaml
- charts/hlf-k8s/README.md
- charts/hlf-k8s/UPGRADE.md
- charts/hlf-k8s/templates/deployment-appchannel-operator.yaml
- charts/hlf-k8s/templates/deployment-chaincode-operator.yaml
- charts/hlf-k8s/templates/deployment-chaincode.yaml
- charts/hlf-k8s/templates/job-hook-delete-secrets.yaml
- charts/hlf-k8s/values.yaml
- examples/2-orgs-policy-any-no-ca/values/org-1-peer-1.yaml
- examples/2-orgs-policy-any-no-ca/values/org-2-peer-1.yaml
- examples/2-orgs-policy-any/values/org-1-peer-1.yaml
- examples/2-orgs-policy-any/values/org-2-peer-1.yaml
- examples/3-orgs-policy-majority/values/org-1-peer-1.yaml
- examples/3-orgs-policy-majority/values/org-2-peer-1.yaml
- examples/3-orgs-policy-majority/values/org-3-peer-1.yaml
- examples/4-orgs-policy-any/values/org-1-peer-1.yaml
- examples/4-orgs-policy-any/values/org-2-peer-1.yaml
- examples/4-orgs-policy-any/values/org-3-peer-1.yaml
- examples/4-orgs-policy-any/values/org-4-peer-1.yaml
- examples/4-orgs-policy-majority/values/org-1-peer-1.yaml
- examples/4-orgs-policy-majority/values/org-2-peer-1.yaml
- examples/4-orgs-policy-majority/values/org-3-peer-1.yaml
- examples/4-orgs-policy-majority/values/org-4-peer-1.yaml
Companion PR: 
- https://github.com/SubstraFoundation/substra-tests/pull/166
We currently don't support using the same chaincode on different channels.
This PR removes this limitation.
Sample use case: solo channels using the same chaincode as shared channels.
> Allow the same chaincode to be used on multiple channels

- images/fabric-tools/Dockerfile
Clément reported an issue that he spotted during the upgrade of Healthchain project with the latest release. It seems that the netcat is not working anymore due to the fact the base image is already packaging netcat.
> remove netcat dependency which seems included in base image

- charts/hlf-k8s/Chart.yaml
- charts/hlf-k8s/templates/deployment-chaincode-operator.yaml
Querying the chaincode list as long as the `chaincode.list` file is empty.
With `netcat -z` you are only checking that something is listening at the specified address.
In my setup the peer is deployed in a kubernetes and accessed through an ingress which is an nginx proxy. If you query the endpoint `peer.xyz.com` there is a service listening, nginx, even if the peer is not started.
This is leading to an issue where on [line 68 of deployment-chaincode-operator](https://github.com/SubstraFoundation/hlf-k8s/blob/master/charts/hlf-k8s/templates/deployment-chaincode-operator.yaml#L68) the file `chaincode.list` is empty.
Then `jq -e '.installed_chaincodes[] | select(.label=="{{ .name }}")' chaincode.list > /dev/null;` return code is 0, so we are effectively skipping the whole install loop.
this …
> Fix empty chaincode.list file in chaincode operator

- examples/2-orgs-policy-any-no-ca/values/org-1-peer-1.yaml
- examples/2-orgs-policy-any-no-ca/values/org-2-peer-1.yaml
- examples/2-orgs-policy-any/values/org-1-peer-1.yaml
- examples/2-orgs-policy-any/values/org-2-peer-1.yaml
- examples/3-orgs-policy-majority/values/org-1-peer-1.yaml
- examples/3-orgs-policy-majority/values/org-2-peer-1.yaml
- examples/3-orgs-policy-majority/values/org-3-peer-1.yaml
- examples/4-orgs-policy-any/values/org-1-peer-1.yaml
- examples/4-orgs-policy-any/values/org-2-peer-1.yaml
- examples/4-orgs-policy-any/values/org-3-peer-1.yaml
- examples/4-orgs-policy-any/values/org-4-peer-1.yaml
- examples/4-orgs-policy-majority/values/org-1-peer-1.yaml
- examples/4-orgs-policy-majority/values/org-2-peer-1.yaml
- examples/4-orgs-policy-majority/values/org-3-peer-1.yaml
- examples/4-orgs-policy-majority/values/org-4-peer-1.yaml
If a user add a new chaincode after deployment, he may run into issue because crshost for certificate is defined at the deployment. Use wildcard in the examples to show that we can generate certificate for a domain.
None
None
Launch one of the examples.
None
> Update crshost to use *.org for potential new chaincodes

- charts/hlf-k8s/Chart.yaml
- charts/hlf-k8s/templates/deployment-appchannel-operator.yaml
- charts/hlf-k8s/templates/deployment-chaincode-operator.yaml
- charts/hlf-k8s/templates/deployment-chaincode.yaml
- charts/hlf-k8s/templates/job-hook-delete-secrets.yaml
This PR moves the following calls from the appchannel operator to the chaincode operator, which removes a bit of  code/complexity.
```
peer lifecycle chaincode checkcommitreadiness
peer lifecycle chaincode querycommitted
peer chaincode invoke --isInit
```
I didn't have to use discovery (as [suggested here](https://github.com/SubstraFoundation/hlf-k8s/pull/102#issuecomment-734149787)) to obtain the peer address and the TLS root cert:
```
--peerAddresses ${PEER_HOST}:${PEER_PORT} 
--tlsRootCertFiles tlsRootCert-$org.crt
```
The reason why we don't need to specify these values is that they are the "default" values taken from `core.yaml` and `/var/hyperledger/tls/client/pair`.
Question : Is it cleaner to pass paramters explicitly (via `--peerAddresses` et `--tlsRootCertFiles`), or to use …
> refactor chaincode operator

- charts/hlf-k8s/CHANGELOG.md
- charts/hlf-k8s/Chart.yaml
- charts/hlf-k8s/README.md
- charts/hlf-k8s/values.yaml
Moved the object `docker.enabled` under the `peer` key.
The docker socket mount was still enabled as the `docker` object was misplaced.
Here is the related documentation: [hlf-peer chart documentation](https://github.com/owkin/charts/blob/afdb2fba2dad2104db2ee1a48b33ceb87cc07913/hlf-peer/README.md#configuration)
Launching the setup with skaffold.
Looking for docker in the resulting chart:
**Before**
```sh
helm template peer -f examples/2-orgs-policy-any-no-ca/values/org-1-peer-1.yaml charts/hlf-k8s | grep docker
CORE_VM_ENDPOINT: unix:///host/var/run/docker.sock
- name: dockersocket
path: /var/run/docker.sock
- mountPath: /host/var/run/docker.sock
name: dockersocket
```
**After**
```sh
helm template peer -f examples/2-orgs-policy-any-no-ca/values/org-1-peer-1.yaml charts/hlf-k8s | grep …
```
> Disable docker socket mount on hlf-peer

- charts/hlf-k8s/CHANGELOG.md
- charts/hlf-k8s/Chart.yaml
- charts/hlf-k8s/templates/deployment-chaincode-operator.yaml
Due to way conditions were written, there was an approval issued on each iteration (approximately every 10s).
This was generating a new transaction each time, increasing block height although there was no real chaincode usage.
With these changes, the loop body is only executed when the condition is met.
> [chaincode-operator] fix multi approval

- README.md
It is preferable to run specific version from images in repository
rather than rebuilding the images from local copy.
This PR is a mirror of https://github.com/SubstraFoundation/substra-backend/pull/369
This is only a documentation change to provide a future-proof way to run previous tags.
A PR on documentation will also be opened.
> [doc] mention how to run specific version

- charts/hlf-k8s/CHANGELOG.md
- charts/hlf-k8s/Chart.yaml
- charts/hlf-k8s/README.md
- charts/hlf-k8s/values.yaml
To avoid potential issue in a deployment, it's better to enable persistence by default
Fix #118 
None
Launch hlf-k8s to see persistence enable by default
None
None
> Set persistence value to true

- README.md
Update the url to hlf documentation in the readme as it is pointing to v.1.4 whereas v2.+ is now implemented.
I have used the `latest` version, but please let me know if it would be better to point towards any specific version
> Update hlf url in readme

- charts/hlf-k8s/CHANGELOG.md
- charts/hlf-k8s/Chart.yaml
- charts/hlf-k8s/templates/deployment-chaincode-operator.yaml
Changed the condition to enter the commit phase in the chaincode operator. Now we should enter only if the `name`, `version` or `sequence` value change, or if there is no chaincode committed.
Changed a `jq` expression used to get the `TLS_ROOT_CERT` from the config to make it work if there is a special character in the `mspid`
In some scenario I was using a mspid containing a `-` and this was preventing the chaincode from being committed with the latest version of this chart, printing a `jq` error in the logs.
```plain
jq: error: syntax error, unexpected IDENT, expecting $end (Unix shell quoting issues?) at <top-level>, line 1:
.msps.Orgnode-1MSP.tls_root_certs[0]
jq: 1 compile error
```
During the resolution of this issue I noticed that the following condition was never resolving to …
> Fix chaincode commit phase in chaincode-operator

- charts/hlf-k8s/CHANGELOG.md
- charts/hlf-k8s/Chart.yaml
- charts/hlf-k8s/templates/deployment-appchannel-operator.yaml
Reduce the delay in the app channel operator between each addition of a organization to the app channel. This makes the network startup faster, especially when there are a lot of orgs.
> reduce delay in app channel operator

- charts/hlf-k8s/CHANGELOG.md
- charts/hlf-k8s/Chart.yaml
- charts/hlf-k8s/templates/deployment-appchannel-operator.yaml
Fixes https://github.com/SubstraFoundation/hlf-k8s/issues/131
﻿
> fix: appchannel incorrect behavior with overlapping channel names

- charts/hlf-k8s/CHANGELOG.md
- charts/hlf-k8s/Chart.yaml
- charts/hlf-k8s/UPGRADE.md
- charts/hlf-k8s/values.yaml
- examples/2-orgs-policy-any-no-ca-same-cc/skaffold.yaml
- examples/2-orgs-policy-any-no-ca/skaffold.yaml
- examples/2-orgs-policy-any/skaffold.yaml
- examples/3-orgs-policy-majority/skaffold.yaml
- examples/4-orgs-policy-any/skaffold.yaml
- examples/4-orgs-policy-majority/skaffold.yaml
Update all example skaffolds to use `substra` instead of `substrafoundation`.
The image repository name was updated in the main skaffold but not in the examples.
> chore: rename substrafoundation to substra

- docker/fabric-tools/Dockerfile
Address this issue:
```shellsession
$ docker build . -f docker/fabric-tools/Dockerfile 
[...]
=> => extracting sha256:aa900656510dd0157ee615f22c06e1e698f033c0ada93f1b00  0.0s
=> [2/5] RUN apk update &&   apk add curl netcat-openbsd vim libc6-compat   4.2s
=> ERROR [3/5] RUN curl -SL https://github.com/hyperledger/fabric-ca/relea  0.3s
------                                                                            
> [3/5] RUN curl -SL https://github.com/hyperledger/fabric-ca/releases/download/v1.5.1/hyperledger-fabric-ca-linux-amd64-1.5.1.tar.gz | tar xz --strip-components=1 &&   mv ./fabric-ca-client /bin:                                                 
#6 0.263 curl: (48) An unknown option was passed in to libcurl                    
#6 0.267 tar: invalid magic
#6 0.268 tar: short …
```
> fix: upgrade fabric-tools libcurl
